{% set name = "pyrte_rrtmgp" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/earth-system-radiation/pyRTE-RRTMGP/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 519893c42f61744776011279f2bad2123f71329126539c2db6f68eed2fea932d

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win or py<311 or py>312]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=1.21.0                         # [build_platform != target_platform]
    - pybind11 >=2.10.0                      # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake >=3.18
    - git >=2.44.0
    - libuv >=1.44.2
    - ninja >=1.10
    - python

  host:
    - numpy >=1.21.0
    - pip
    - pybind11 >=2.10.0
    - python
    - rte_rrtmgp ==1.9.1
    - scikit-build-core

  run:
    - netcdf4 >=1.7.2
    - numpy >=1.21.0
    - pytest >=7.4
    - python
    - requests >=2.4.0
    - rte_rrtmgp ==1.9.1
    - xarray >=2023.5.0

test:
  imports:
    - pyrte_rrtmgp
  requires:
    - netcdf4 >=1.7.2
    - numpy >=1.21
    - pytest >=7.4
    - requests >=2.4.0
    - rte_rrtmgp ==1.9.1
    - xarray >=2023.5.0
  commands:
    - pyrte_rrtmgp run_tests

about:
  home: https://github.com/earth-system-radiation/pyRTE-RRTMGP
  summary: A Python interface to the RTE+RRTMGP Fortran software package.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://pyrte-rrtmgp.readthedocs.io/

extra:
  recipe-maintainers:
    - brendancol
    - giancastro
    - makepath-alex
    - RobertPincus
