schema_version: 1

context:
  name: pyrte_rrtmgp
  version: "0.2.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/earth-system-radiation/pyRTE-RRTMGP/archive/refs/tags/v${{ version }}.tar.gz
    sha256: cf9cae2b5bdf65db18d62acd7325073954673f7b10ef9d64b969e0d76ed3b21a

build:
  number: 2
  skip: match(python, "<3.11") or match(python, ">3.14")
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: numpy >=1.21.0
    - if: build_platform != target_platform
      then: pybind11 >=2.10.0
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ stdlib('c') }}                # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib('m2w64_c') }}          # [win]
  
    - cmake >=3.18
    - git >=2.44.0
    - libuv >=1.44.2
    - ninja >=1.10
    - python
  host:
    - numpy >=1.21.0
    - pip
    - pybind11 >=2.10.0
    - python
    - rte_rrtmgp ==1.9.2
    - scikit-build-core
  run:
    - netcdf4 >=1.7.2
    - numpy >=1.21.0
    - pytest >=7.4
    - pytest-cov >=3.0
    - python
    - requests >=2.4.0
    - pandas <3.0.0
    - rte_rrtmgp ==1.9.2
    - xarray >=2023.5.0
    - dask >=2023.5.0

tests:
  - python:
      imports:
        - pyrte_rrtmgp
      pip_check: false
  - requirements:
      run:
        - netcdf4 >=1.7.2
        - numpy >=1.21
        - pytest >=7.4
        - pytest-cov >=3.0
        - requests >=2.4.0
        - pandas <3.0.0
        - rte_rrtmgp ==1.9.2
        - xarray >=2023.5.0
        - dask >=2023.5.0
    script:
      - pyrte_rrtmgp run_tests

about:
  summary: A Python interface to the RTE+RRTMGP Fortran software package.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/earth-system-radiation/pyRTE-RRTMGP
  documentation: https://pyrte-rrtmgp.readthedocs.io/

extra:
  recipe-maintainers:
    - brendancol
    - giancastro
    - makepath-alex
    - RobertPincus
